apiVersion: v1
kind: Service
metadata:
  name: carrito
  labels:
    name: carrito-service
    app: tiendavirtual
spec:
  selector:
    name: carrito-deployment
    app: tiendavirtual
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer