apiVersion: v1
kind: Service
metadata:
  name: cds
  labels:
    name: cds-service
    app: tiendavirtual
spec:
  selector:
    name: cds-deployment
    app: tiendavirtual
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer